### ISSUE TITLE
找不到<bits/types/FILE.h>

### ISSUE THREAD

**Issue by zouxingyu** [ltoddy/scheme.c#32]
请问在windows上编译的时候发生include错误，找不到这个<bits/types/FILE.h>文件，怎么解决呢

**Comment by ltoddy** [comment]
我新提交了一个commit, 我这个解决了,  源代码中使用<bits/types/FILE.h> 这个东西, 是为了使用 FILE 这个文件结构体, 所以把<bits/types/FILE.h>改成<stdio.h> 就可以了.
